public class InterfazAmistoso extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAmistoso
     */
    public InterfazAmistoso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        chkHumano1 = new javax.swing.JCheckBox();
        chkHumano2 = new javax.swing.JCheckBox();
        comboEquipo1 = new javax.swing.JComboBox();
        comboEquipo2 = new javax.swing.JComboBox();
        btEquipo1 = new javax.swing.JButton();
        btEquipo2 = new javax.swing.JButton();
        btJugar = new javax.swing.JButton();
        btVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkHumano1.setText("¿Humano?");
        chkHumano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHumano1ActionPerformed(evt);
            }
        });

        chkHumano2.setText("¿Humano?");
        chkHumano2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHumano2ActionPerformed(evt);
            }
        });

        comboEquipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "at madrid", "betis" }));
        comboEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipo1ActionPerformed(evt);
            }
        });

        comboEquipo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "at madrid", "betis" }));
        comboEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipo2ActionPerformed(evt);
            }
        });

        btEquipo1.setText("Ver");
        btEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEquipo1ActionPerformed(evt);
            }
        });

        btEquipo2.setText("Ver");
        btEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEquipo2ActionPerformed(evt);
            }
        });

        btJugar.setText("Jugar");
        btJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkHumano1)
                    .addComponent(chkHumano2)
                    .addComponent(btJugar))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEquipo2)
                    .addComponent(btEquipo1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboEquipo1, 0, 105, Short.MAX_VALUE)
                        .addComponent(comboEquipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btVolver))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHumano1)
                    .addComponent(comboEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEquipo1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkHumano2)
                    .addComponent(comboEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEquipo2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btJugar)
                    .addComponent(btVolver))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	String nombreEquipo1 = comboEquipo1.getSelectedItem().toString();
    	Plantilla equipo1 = new Plantilla(nombreEquipo1);
    	
    	InterfazConvocados ic = new InterfazConvocados(equipo1);
    	ic.setVisible(true);
    }                                         

    private void btEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	String nombreEquipo2 = comboEquipo2.getSelectedItem().toString();
    	Plantilla equipo2 = new Plantilla(nombreEquipo2);
    	
    	InterfazConvocados ic2 = new InterfazConvocados(equipo2);
    	ic2.setVisible(true);
    }                                         

    private void chkHumano1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void chkHumano2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void comboEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void comboEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {
        String nombreEquipo1 = comboEquipo1.getSelectedItem().toString();
    	
    	String nombreEquipo2 = comboEquipo2.getSelectedItem().toString();

    	Manager[] managers = new Manager[2];
    	
    	managers[0] = new Manager(nombreEquipo1, false);
    	
    	managers[1] = new Manager(nombreEquipo2, false);
    	
    	Partido amistoso = new Partido(managers);        	
    	
    	InterfazResultado ir = new InterfazResultado(managers, amistoso.jugarPartido());
    	ir.setVisible(true);
    	this.setVisible(false);
    }

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        InterfazPrincipal ip = new InterfazPrincipal();
        ip.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfazAmistoso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton btEquipo1;
    private javax.swing.JButton btEquipo2;
    private javax.swing.JButton btJugar;
    private javax.swing.JButton btVolver;
    private javax.swing.JCheckBox chkHumano1;
    private javax.swing.JCheckBox chkHumano2;
    private javax.swing.JComboBox comboEquipo1;
    private javax.swing.JComboBox comboEquipo2;
    // End of variables declaration
}

