public class InterfazResultado extends javax.swing.JFrame {

	int[] resultado = new int[2];
	Manager[] managers = new Manager[2];
    /**
     * Creates new form InterfazResultado
     */
    public InterfazResultado(Manager[] managers, int[] resultado) {
        initComponents(managers, resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Manager[] managers, int[] resultado) {
    	this.resultado = resultado;
    	this.managers = managers;
        lbEquipo1 = new javax.swing.JLabel(managers[0].getEquipo().getNombre());
        lbEquipo2 = new javax.swing.JLabel(managers[1].getEquipo().getNombre());
        jScrollPane1 = new javax.swing.JScrollPane();
        pantxtEquipo1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantxtEquipo2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTarjetas2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaLesionados2 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaTarjetas1 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaLesionados1 = new javax.swing.JList();
        btCambiar = new javax.swing.JButton();
        btJugarSiguiente = new javax.swing.JButton();
        btAceptar = new javax.swing.JButton("Aceptar");
        
        //Ponemos los resultados en las cajas de texto
        pantxtEquipo1.setText(String.valueOf(this.resultado[0]));
        pantxtEquipo2.setText(String.valueOf(this.resultado[1]));


        //this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(pantxtEquipo1);

        jScrollPane2.setViewportView(pantxtEquipo2);

        listaTarjetas2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaTarjetas2);

        listaLesionados2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaLesionados2);

        listaTarjetas1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(listaTarjetas1);

        listaLesionados1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(listaLesionados1);

        btCambiar.setText("Cambiar jugadores");
        btCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarActionPerformed(evt);
            }
        });
        
        btAceptar.setText("Aceptar");
        btAceptar.setVisible(false);
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btJugarSiguiente.setText("Jugar 2ª parte");
        btJugarSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lbEquipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEquipo2)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCambiar)
                        .addComponent(btAceptar)
                        .addGap(76, 76, 76)
                        .addComponent(btJugarSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(76, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEquipo1)
                    .addComponent(lbEquipo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCambiar)
                    .addComponent(btAceptar)
                    .addComponent(btJugarSiguiente))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btCambiarActionPerformed(java.awt.event.ActionEvent evt) {
        InterfazCambios ic = new InterfazCambios();
        ic.setVisible(true);
    }
    
    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {
    	this.setVisible(false);
    	InterfazPrincipal ip = new InterfazPrincipal();
    	ip.setVisible(true);
    }

    private void btJugarSiguienteActionPerformed(java.awt.event.ActionEvent evt) {
    	Partido amistoso = new Partido(managers);  
    	int[] res = amistoso.jugarPartido();
    	resultado[0]+=res[0];
    	resultado[1]+=res[1];
    	//Ponemos los resultados en las cajas de texto
        pantxtEquipo1.setText(String.valueOf(this.resultado[0]));
        pantxtEquipo2.setText(String.valueOf(this.resultado[1]));
        btJugarSiguiente.setVisible(false);
        btCambiar.setVisible(false);
        btAceptar.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btCambiar;
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btJugarSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbEquipo1;
    private javax.swing.JLabel lbEquipo2;
    private javax.swing.JList listaLesionados1;
    private javax.swing.JList listaLesionados2;
    private javax.swing.JList listaTarjetas1;
    private javax.swing.JList listaTarjetas2;
    private javax.swing.JTextPane pantxtEquipo1;
    private javax.swing.JTextPane pantxtEquipo2;
    // End of variables declaration
}
